assets:
  settings.xml: yegor256/home#assets/s3auth/settings.xml 
merge:
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
  script: 
    - "mvn help:system clean install -Pqulice --settings ../settings.xml"
