language: java
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
install:
  - travis_retry sudo apt-get install -y --fix-missing libmagic1 libmagic-dev
  - gem install pdd
script:
  - pdd --file=/dev/null
  - mvn clean install -Pqulice --batch-mode --errors --quiet
